name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  read-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read Tag from File
        id: set_tag
        run: |
          tag=$(cat qmk_tag | tr -d "[:space:]")
          echo "tag=$tag" >> $GITHUB_OUTPUT

  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    needs: read-tag
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: ${{ needs.read-tag.outputs.tag }}

  publish:
    name: 'QMK Userspace Publish'
    if: always() && !cancelled()
    needs: build
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@main
    with:
      release_name: ${{ github.ref_name }}
